table 1-007-0033
	lineageTag: ddf34b43-4337-49b4-83fa-d52b2c0d332f

	column №
		dataType: int64
		formatString: 0
		lineageTag: ebb137c9-c894-4d93-bfa2-b965a7f3fad0
		summarizeBy: sum
		sourceColumn: №

		annotation SummarizationSetBy = Automatic

	column 'Hududlar nomi'
		dataType: string
		lineageTag: 8d59c48e-171f-4250-b754-dbcd25f5811d
		summarizeBy: none
		sourceColumn: Hududlar nomi

		annotation SummarizationSetBy = Automatic

	column '100 000 аhоliga nisbatan'
		dataType: double
		lineageTag: a9b92622-c2c9-43d3-aea1-863d4420c0b5
		summarizeBy: sum
		sourceColumn: 100 000 аhоliga nisbatan

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition 1-007-0033 = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\ACER\Downloads\Aholining birlamchi kasallanishi ko‘rsatkichi 100 000 aholiga nisbatan.xlsx"), null, true),
				    #"1-007-0033_Sheet" = Source{[Item="1-007-0033",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(#"1-007-0033_Sheet", [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"№", Int64.Type}, {"Hududlar nomi", type text}, {"100 000 аhоliga nisbatan", type number}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

