table 1-007-0011
	lineageTag: 251967af-44ab-4eef-9292-597c0fa31e20

	column №
		dataType: int64
		formatString: 0
		lineageTag: 1a55bd2b-b92d-47ab-82a8-0da8e58890f8
		summarizeBy: sum
		sourceColumn: №

		annotation SummarizationSetBy = Automatic

	column 'Hududlar nomi'
		dataType: string
		lineageTag: 43dec1f7-ae30-4995-9364-c9996984d6e0
		summarizeBy: none
		sourceColumn: Hududlar nomi

		annotation SummarizationSetBy = Automatic

	column 'Go''daklar o''limi 1000 tirik tug''ilishga'
		dataType: double
		lineageTag: 1c6b54b8-a1f6-415f-9172-18c00bffb890
		summarizeBy: sum
		sourceColumn: Go'daklar o'limi 1000 tirik tug'ilishga

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition 1-007-0011 = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\ACER\Downloads\Go‘daklar o‘limi.xlsx"), null, true),
				    #"1-007-0011_Sheet" = Source{[Item="1-007-0011",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(#"1-007-0011_Sheet", [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"№", Int64.Type}, {"Hududlar nomi", type text}, {"Go'daklar o'limi 1000 tirik tug'ilishga", type number}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

