table 1-007-0022
	lineageTag: 4c850801-ec25-4ec5-a83a-add745002a07

	column №
		dataType: int64
		formatString: 0
		lineageTag: 9240a42f-a01f-4905-b1fb-f254bf42bc0f
		summarizeBy: sum
		sourceColumn: №

		annotation SummarizationSetBy = Automatic

	column 'Hududlar nomi'
		dataType: string
		lineageTag: 171d0e7f-5ac8-433f-bd41-5c477e4ffa18
		summarizeBy: none
		sourceColumn: Hududlar nomi

		annotation SummarizationSetBy = Automatic

	column 'Jami.Mutlоq rakamda'
		dataType: int64
		formatString: 0
		lineageTag: da4c9bee-1fc3-46af-89b6-de5287ca033f
		summarizeBy: sum
		sourceColumn: Jami.Mutlоq rakamda

		annotation SummarizationSetBy = Automatic

	column 'Jami.10 000 аhоliga nisbatan taminoti.'
		dataType: string
		lineageTag: 3095ffac-ec6d-41b1-89cb-3a486e6c19c3
		summarizeBy: none
		sourceColumn: Jami.10 000 аhоliga nisbatan taminoti.

		annotation SummarizationSetBy = Automatic

	partition 1-007-0022 = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\ACER\Downloads\Shifo o‘rinlari soni va 10 ming aholiga nisbatan ko‘rsatkichi.xlsx"), null, true),
				    #"1-007-0022_Sheet" = Source{[Item="1-007-0022",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(#"1-007-0022_Sheet", [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"№", Int64.Type}, {"Hududlar nomi", type text}, {"Jami.Mutlоq rakamda", Int64.Type}, {"Jami.10 000 аhоliga nisbatan taminoti.", type any}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

